version: 0.2

phases:
  
  pre_build:
    commands:
      - echo login to Amazon ECR
      - aws --version
      - echo $AWS_DEFAULT_REGION
      - $(aws ecr get-login --no-include-email --region us-east-1)

  build:
    commands:
      - REPOSITORY_URI=939138653191.dkr.ecr.us-east-1.amazonaws.com/aaa 
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://140.82.112.3:443 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
    
  build:
    commands:
      - echo Build started on 'date'
      - echo Building the Docker image 
      - docker build -t $REPOSITORY_URI:latest
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on 'date'
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing definitions file...
      - printf '[{"name":"exp-code-pipeline","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json                 

